services:
  user-service:
    build: ./backend/user-service
    environment:
      - MONGO_URL=${MONGO_URI_USERS}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - ecommerce-network
    depends_on:
      - mongo
    deploy:
      replicas: 2

  product-service:
    build: ./backend/product-service
    environment:
      - MONGO_URI=${MONGO_URI_PRODUCTS}
    networks:
      - ecommerce-network
    depends_on:
      - mongo
    deploy:
      replicas: 2

  shopping-cart-service:
    build: ./backend/shopping-cart-service
    environment:
      - MONGO_URI=${MONGO_URI_CART}
      - PRODUCT_SERVICE_URI=http://product-service:5001
    networks:
      - ecommerce-network
    depends_on:
      - mongo
      - product-service
    deploy:
      replicas: 2

  order-service:
    build: ./backend/order-service
    environment:
      - MONGO_URI=${MONGO_URI_ORDER}
      - PRODUCT_SERVICE_URI=http://product-service:5001
    depends_on:
      - mongo
      - product-service
    networks:
      - ecommerce-network
    deploy:
      replicas: 2

  payment-service:
    build: ./backend/payment-service
    environment:
      - MONGO_URI=${MONGO_URI_PAYMENT}
      - MOMO_SECRET_KEY=${MOMO_SECRET_KEY}
    depends_on:
      - mongo
    networks:
      - ecommerce-network
    deploy:
      replicas: 2

  notification-service:
    build: ./backend/notification-service
    environment:
      - NODEMAILER_EMAIL=${NODEMAILER_EMAIL}
      - NODEMAILER_PASSWORD=${NODEMAILER_PASSWORD}
    networks:
      - ecommerce-network
    deploy:
      replicas: 2

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ecommerce-network
    depends_on:
      - user-service
      - product-service
      - shopping-cart-service
      - order-service
      - payment-service
      - notification-service

volumes:
  mongo-data:

networks:
  ecommerce-network:
    driver: bridge
