
services:
  user-service:
    build: ./user-service
    ports:
      - 5000:5000
    environment:
      - MONGO_URL=${MONGO_URI_USERS}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  product-service:
    build: ./product-service
    ports:
      - 5001:5001
    environment:
      - MONGO_URI=${MONGO_URI_PRODUCTS}
    depends_on:
      - mongo

  shopping-cart-service:
    build: ./shopping-cart-service
    ports:
      - 5002:5002
    environment:
      - MONGO_URI=${MONGO_URI_CART}
      - PRODUCT_SERVICE_URI=http://product-service:5001
    depends_on:
      - mongo
      - product-service
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

